// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package emp

import (
	"gf-admin/api/emp"
)

type ControllerV1 struct{}

func NewV1() emp.IEmpV1 {
	return &ControllerV1{}
}
